import { indexStore } from "@/lib/data/store";
import { addPeriods, currentPeriod, daysSince, daysUntil, lastPeriods, periodOf, previousPeriod, today } from "@/lib/date";
import { collectionRate } from "@/lib/derived/metrics";
import { isOccupying } from "@/lib/derived/occupancy";
import { formatMoney, formatPercent, labelize } from "@/lib/format";
import { getSuppliers } from "@/lib/queries";
import type { AlertSeverity, ISODate, Store } from "@/types";

export interface Insight {
  id: string;
  text: string;
  /** Screen that shows the underlying data. */
  href: string;
  tone: AlertSeverity | "success";
  weight: number;
  /** Where the number comes from, for the tooltip. */
  source: string;
}

const MAINTENANCE_CATEGORIES = new Set<string>(["maintenance", "elevator", "plumbing", "electrical", "hvac", "generator", "appliance", "painting", "pest_control"]);

/**
 * Dashboard insights (plan §10): three to five specific, high-value facts,
 * each computed from the records and linked to the screen that proves it.
 * Nothing here is generated by a model.
 */
export function getInsights(store: Store, base: ISODate = today(), limit = 5): Insight[] {
  const idx = indexStore(store);
  const t = store.settings.thresholds;
  const out: Insight[] = [];
  const period = periodOf(base);
  const prev = previousPeriod(period);

  /* Maintenance spend vs the six-month average, per building. */
  for (const p of store.properties) {
    const spend = (per: string) => store.expenses.filter((e) => !e.deleted && e.propertyId === p.id && e.classification === "operating" && (e.workOrderId || MAINTENANCE_CATEGORIES.has(e.category)) && periodOf(e.expenseDate) === per).reduce((n, e) => n + e.amount, 0);
    const history = lastPeriods(6, prev).map(spend);
    const avg = history.reduce((n, x) => n + x, 0) / history.length;
    const now = spend(period);
    if (avg > 0 && now > avg * t.maintenanceCostHighMultiplier) {
      out.push({ id: `maint-${p.id}`, text: `${p.name} maintenance spending is ${formatPercent(now / avg - 1)} above its 6-month average (${formatMoney(now)} vs ${formatMoney(Math.round(avg))}).`, href: `/analytics/maintenance?property=${p.id}`, tone: "warning", weight: 400 + (now - avg), source: "Operating maintenance expenses this month vs the previous six months" });
    }
  }

  /* Repeat issues on one unit. */
  const groups = new Map<string, { unitId: string; propertyId: string; category: string; count: number }>();
  for (const w of store.workOrders) {
    if (!w.unitId || w.status === "cancelled" || daysSince(w.reportedAt) > t.repeatIssueWindowDays) continue;
    const key = `${w.unitId}|${w.category}`;
    const g = groups.get(key) ?? { unitId: w.unitId, propertyId: w.propertyId, category: w.category, count: 0 };
    g.count += 1;
    groups.set(key, g);
  }
  for (const g of [...groups.values()].filter((x) => x.count >= t.repeatIssueMinCount).sort((a, b) => b.count - a.count).slice(0, 2)) {
    const unit = idx.unitById.get(g.unitId);
    const property = idx.propertyById.get(g.propertyId);
    if (!unit || !property) continue;
    out.push({ id: `repeat-${g.unitId}-${g.category}`, text: `${property.name} ${unit.unitNumber} has had ${g.count} ${labelize(g.category).toLowerCase()} work orders in ${t.repeatIssueWindowDays} days — a permanent fix will be cheaper than the next call-out.`, href: `/units/${unit.id}?tab=maintenance`, tone: "warning", weight: 350 + g.count * 50, source: "Work orders on the unit within the repeat-issue window" });
  }

  /* Contracts expiring within 30 days. */
  const expiring = store.contracts.filter((c) => isOccupying(c) && daysUntil(c.endDate) >= 0 && daysUntil(c.endDate) <= 30 && c.renewalDecision !== "renew");
  if (expiring.length > 0) {
    const rent = expiring.reduce((n, c) => n + c.monthlyRent, 0);
    out.push({ id: "expiring-30", text: `${expiring.length} contract${expiring.length === 1 ? "" : "s"} worth ${formatMoney(rent)}/month expire within 30 days without a renewal agreed.`, href: "/contracts?expiring=30", tone: expiring.length >= 3 ? "critical" : "warning", weight: 300 + rent / 10, source: "Occupying contracts ending within 30 days, renewal not confirmed" });
  }

  /* Tenants owing more than 60 days of rent. */
  const owing = new Map<string, number>();
  for (const p of store.payments) if ((p.status === "overdue" || p.status === "partial") && daysSince(p.dueDate) > 60) owing.set(p.tenantId, (owing.get(p.tenantId) ?? 0) + (p.amountDue - p.amountPaid));
  if (owing.size > 0) {
    const total = [...owing.values()].reduce((n, x) => n + x, 0);
    out.push({ id: "owing-60", text: `${owing.size} tenant${owing.size === 1 ? "" : "s"} owe rent more than 60 days old — ${formatMoney(total)} in total.`, href: "/payments?status=overdue", tone: "critical", weight: 500 + total / 10, source: "Overdue or partial instalments due more than 60 days ago" });
  }

  /* Longest vacancy. */
  const vacant = store.units.filter((u) => u.status === "available" && u.availableSince).sort((a, b) => (a.availableSince! < b.availableSince! ? -1 : 1))[0];
  if (vacant && daysSince(vacant.availableSince!) >= t.vacantWarningDays) {
    const property = idx.propertyById.get(vacant.propertyId);
    const days = daysSince(vacant.availableSince!);
    const ref = vacant.lastRent ?? vacant.marketRent ?? vacant.askingRent;
    out.push({ id: `vacant-${vacant.id}`, text: `${property?.name ?? ""} ${vacant.unitNumber} has been vacant for ${days} days${ref ? ` — about ${formatMoney(Math.round((ref / 30) * days))} of rent not earned` : ""}.`, href: `/units/${vacant.id}`, tone: days >= t.vacantCriticalDays ? "critical" : "warning", weight: 200 + days * 3, source: "Days since the unit became available, at its reference rent" });
  }

  /* Collection rate vs last month. */
  const now = collectionRate(store.payments, period, base);
  const before = collectionRate(store.payments, prev);
  if (now.due > 0 && before.due > 0 && before.rate - now.rate >= 0.1) {
    out.push({ id: "collection-drop", text: `Collection is at ${formatPercent(now.rate)} this month against ${formatPercent(before.rate)} last month — ${formatMoney(now.due - now.collected)} still to come in.`, href: "/finance/rent-roll", tone: "warning", weight: 280 + (before.rate - now.rate) * 1000, source: "Rent collected ÷ rent due, this month vs last" });
  }

  /* Supplier with a high repeat-issue rate. */
  const worst = getSuppliers(store).filter((r) => r.repeatIssueRate !== null && r.completedJobs >= 3).sort((a, b) => (b.repeatIssueRate ?? 0) - (a.repeatIssueRate ?? 0))[0];
  if (worst && (worst.repeatIssueRate ?? 0) >= 0.4) {
    out.push({ id: `supplier-${worst.supplier.id}`, text: `${formatPercent(worst.repeatIssueRate ?? 0)} of ${worst.supplier.name}'s jobs came back within the repeat window — consider another ${labelize(worst.supplier.category).toLowerCase()} supplier.`, href: `/suppliers/${worst.supplier.id}`, tone: "attention", weight: 220 + (worst.repeatIssueRate ?? 0) * 100, source: "Completed jobs followed by the same issue on the same unit or asset" });
  }

  /* Projects over budget. */
  for (const r of store.renovations.filter((x) => (x.status === "in_progress" || x.status === "on_hold") && x.budget > 0 && x.actualCost > x.budget).slice(0, 1)) {
    out.push({ id: `project-${r.id}`, text: `${r.title} is ${formatPercent(r.actualCost / r.budget - 1)} over budget (${formatMoney(r.actualCost)} of ${formatMoney(r.budget)}) at ${r.progressPercent}% complete.`, href: `/renovations/${r.id}`, tone: "warning", weight: 260 + (r.actualCost - r.budget) / 10, source: "CapEx booked against the project vs its budget" });
  }

  /* Overdue preventive services. */
  const overdueServices = store.preventivePlans.filter((p) => p.status === "active" && p.nextServiceDate < base);
  if (overdueServices.length > 0) {
    out.push({ id: "services-overdue", text: `${overdueServices.length} preventive service${overdueServices.length === 1 ? " is" : "s are"} overdue, including ${overdueServices.sort((a, b) => (a.nextServiceDate < b.nextServiceDate ? -1 : 1))[0].maintenanceType.toLowerCase()} due ${overdueServices[0].nextServiceDate}.`, href: "/maintenance/preventive?state=overdue", tone: "attention", weight: 180 + overdueServices.length * 40, source: "Active preventive plans past their next service date" });
  }

  /* Something good, when the rest is quiet. */
  if (out.length < 3) {
    const paid = store.payments.filter((p) => p.paidDate && p.paidDate > addPeriods(period, 0) + "-00" && periodOf(p.paidDate) === period);
    if (paid.length > 0) out.push({ id: "collected", text: `${formatMoney(paid.reduce((n, p) => n + p.amountPaid, 0))} collected so far in ${labelize(period)} across ${paid.length} payment${paid.length === 1 ? "" : "s"}.`, href: "/payments", tone: "success", weight: 50, source: "Payments received this month" });
  }

  void currentPeriod;
  return out.sort((a, b) => b.weight - a.weight).slice(0, limit);
}
